name: Container Test

on: [push]

jobs:
  build:
    name: Install IHEPDIRAC
    runs-on: self-hosted
    container:
      image: ihepdirac/sl6-ihepdirac-base
    steps:
      - name: dirac-distribution
        run: |
          pwd
          . /opt/dirac-client/DIRAC/v6r22/bashrc
          dirac-distribution -l IHEP -r v0r1 -D release
          ls -Al release
      - name: CVMFS
        run: |
          pwd
          mkdir -p /cvmfs/dcomputing.ihep.ac.cn/dirac/IHEPDIRAC/${{ github.ref }}
          ls -Al /cvmfs/dcomputing.ihep.ac.cn/dirac/IHEPDIRAC
