name: Container Test

on: [push]

jobs:
  build:
    name: Install IHEPDIRAC
    runs-on: self-hosted
    container:
      image: sl:6
    steps:
      - name: Download dirac-install
        run: |
          pwd
          mkdir ihepdirac && cd ihepdirac
          wget -np -O dirac-install https://github.com/DIRACGrid/DIRAC/raw/integration/Core/scripts/dirac-install.py --no-check-certificate
          chmod +x dirac-install
          ./dirac-install -V IHEP
          source bashrc
          dirac-distribution
