name: Container Test

on: [push]

jobs:
  build:
    name: Install IHEPDIRAC
    runs-on: self-hosted
    container:
      image: ihepdirac/sl6-ihepdirac-base
    steps:
      - name: Setup ssh key
        run: |
          rm -rf key
          mkdir -p key
          echo "${{ secrets.IHEPDIRAC_KEY }}" > key/id_rsa
          chmod 400 key/id_rsa
      - name: Create IHEPDIRAC distribution
        run: |
          . /opt/dirac-client/DIRAC/v6r22/bashrc
          rm -rf release
          dirac-distribution -l IHEP -r v0r1 -D release
          ls -Al release
          cd release
          tar -cf - * | ssh -i ../key/id_rsa -o StrictHostKeyChecking=no www@dirac-code.ihep.ac.cn 'cd /home/www/temp/var/www/html/ihep/tars && tar -xvf - && ls *.tar.gz > tars.list'
      - name: CVMFS
        run: |
          pwd
          mkdir -p /cvmfs/dcomputing.ihep.ac.cn/dirac/IHEPDIRAC/${{ github.ref }}
          ls -Al /cvmfs/dcomputing.ihep.ac.cn/dirac/IHEPDIRAC
