name: Container Test

on: [push]

jobs:
  build:
    name: Install IHEPDIRAC
    runs-on: self-hosted
    container:
      image: sl:6
    steps:
      - name: Install packages
        run: yum install -y git
      - name: Download dirac-install
        run: |
          pwd
          mkdir ihepdirac && cd ihepdirac
          curl -sSLfk -o dirac-install https://github.com/DIRACGrid/DIRAC/raw/integration/Core/scripts/dirac-install.py
          chmod +x dirac-install
          ./dirac-install -V IHEP
      - name: dirac-distribution
        run: |
          pwd
          source ihepdirac/bashrc
          dirac-distribution -l IHEP -r v0r1 -D release
          ls -Al release
      - name: CVMFS
        run: |
          pwd
          mkdir -p /cvmfs/dcomputing.ihep.ac.cn/dirac/IHEPDIRAC/${{ github.ref }}
