name: Container Test

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Install IHEPDIRAC
    runs-on: self-hosted
    container:
      image: ihepdirac/sl6-ihepdirac-base
    steps:
      - name: Setup ssh key
        run: |
          rm -rf key
          mkdir -p key
          echo "${{ secrets.IHEPDIRAC_KEY }}" > key/id_rsa
          chmod 400 key/id_rsa
      - name: Set tag env
        run: echo ::set-env name=GIT_TAG::${GITHUB_REF##*/}
      - name: Create IHEPDIRAC distribution
        run: |
          echo "Current tag: ${GIT_TAG}"
          . /opt/dirac-client/DIRAC/v6r22/bashrc
          rm -rf release
          dirac-distribution -l IHEP -r ${GIT_TAG} -D release
          ls -Al release
          cd release
          tar -cf - * | ssh -i ../key/id_rsa -o StrictHostKeyChecking=no www@dirac-code.ihep.ac.cn 'cd /home/www/temp/var/www/html/ihep/tars && tar -xvf - && ls *.tar.gz > tars.list'
      - name: Install IHEPDIRAC client
        run: |
          mkdir -p /cvmfs/dcomputing.ihep.ac.cn/dirac/IHEPDIRAC/${GIT_TAG}
          cd /cvmfs/dcomputing.ihep.ac.cn/dirac/IHEPDIRAC/${GIT_TAG}
          curl -fsSLk -o dirac-install https://github.com/DIRACGrid/DIRAC/raw/integration/Core/scripts/dirac-install.py
          chmod +x dirac-install
          ./dirac-install -V IHEP -r ${GIT_TAG}
      - name: Set temp data dir
        run: echo ::set-env name=DATA_DIR::$(ssh -i key/id_rsa -o StrictHostKeyChecking=no zhaoxh@lxslc601.ihep.ac.cn 'mktemp --suffix=-deploy -d')
      - name: Prepare data files
        run: |
          echo "Data dir: ${DATA_DIR}"
          tar -czf - /cvmfs/dcomputing.ihep.ac.cn/dirac/IHEPDIRAC/${GIT_TAG} | ssh -i key/id_rsa -o StrictHostKeyChecking=no zhaoxh@lxslc601.ihep.ac.cn "cat > ${DATA_DIR}/${GIT_TAG}.tar.gz"
          echo "${{ secrets.CVMFS_PASS }}" | ssh -i key/id_rsa -o StrictHostKeyChecking=no zhaoxh@lxslc601.ihep.ac.cn "cat > ${DATA_DIR}/cvmfs-pass"
          ls -Al "${DATA_DIR}"
#      - name: Clean data files
#        run: rm -rf "${DATA_DIR}"
